<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class ProductController extends Controller
{
    public function showByNameAndBrand($name, $brand)
    {
        $products = [
            [
                "name" => "Laptop",
                "brand" => "Asus",
                "price" => 50000,
                "screen_size" => 15.6,
                "processor" => "Intel Core i7",
                "ram" => "16GB",
                "storage" => "512GB SSD",
                "description" => "A high-performance laptop from Asus with a powerful Intel Core i7 processor and ample RAM for multitasking.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Lenovo",
                "price" => 150000,
                "screen_size" => 14,
                "processor" => "Intel Core i9",
                "ram" => "32GB",
                "storage" => "1TB NVMe SSD",
                "description" => "Lenovo's flagship laptop featuring an Intel Core i9 processor and a spacious 1TB NVMe SSD for storage.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Dell",
                "price" => 75000,
                "screen_size" => 13.3,
                "processor" => "AMD Ryzen 9",
                "ram" => "16GB",
                "storage" => "512GB NVMe SSD",
                "description" => "A sleek and powerful Dell laptop with an AMD Ryzen 9 processor and fast NVMe SSD storage.",
            ],
            [
                "name" => "Laptop",
                "brand" => "HP",
                "price" => 60000,
                "screen_size" => 15.6,
                "processor" => "Intel Core i5",
                "ram" => "8GB",
                "storage" => "256GB SSD",
                "description" => "An affordable HP laptop with an Intel Core i5 processor and a speedy SSD for quick boot times.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Acer",
                "price" => 45000,
                "screen_size" => 14,
                "processor" => "AMD Ryzen 5",
                "ram" => "12GB",
                "storage" => "256GB SSD",
                "description" => "A budget-friendly Acer laptop powered by an AMD Ryzen 5 processor and ample RAM for smooth performance.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Mi",
                "price" => 20000,
                "screen_size" => 6.5,
                "processor" => "SD 780",
                "ram" => "8gb",
                "storage" => "128GB",
                "description" => "A budget-friendly Mi smartphone with a 48MP dual-camera setup and ample storage capacity.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Samsung",
                "price" => 25000,
                "screen_size" => 6.2,
                "processor" => "64MP Triple Camera",
                "storage" => "256GB",
                "ram" => "4500mAh",
                "description" => "Samsung's latest smartphone featuring a 64MP triple-camera system and a large battery for extended usage.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Apple",
                "price" => 80000,
                "screen_size" => 6.1,
                "processor" => "12MP Dual Camera",
                "storage" => "128GB",
                "ram" => "3800mAh",
                "description" => "The iconic iPhone from Apple with a powerful dual-camera system and ample storage for your apps and media.",
            ],
            [
                "name" => "Mobile",
                "brand" => "OnePlus",
                "price" => 35000,
                "screen_size" => 6.4,
                "processor" => "48MP Quad Camera",
                "storage" => "256GB",
                "ram" => "4200mAh",
                "description" => "OnePlus's flagship smartphone with a versatile quad-camera setup and generous storage capacity.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Google",
                "price" => 60000,
                "screen_size" => 5.8,
                "processor" => "12.2MP Rear Camera",
                "storage" => "128GB",
                "ram" => "3140mAh",
                "description" => "Google's Pixel phone known for its exceptional camera quality and clean Android experience.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Apple",
                "price" => 40000,
                "screen_size" => 10.2,
                "processor" => "Apple A13 Bionic",
                "storage" => "256GB",
                "ram" => "483 grams",
                "description" => "Apple's latest tablet with a powerful A13 Bionic chip and ample storage for all your needs.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Samsung",
                "price" => 35000,
                "screen_size" => 9.7,
                "processor" => "Samsung Exynos",
                "storage" => "128GB",
                "ram" => "420 grams",
                "description" => "Samsung's compact and lightweight tablet with a capable Exynos processor and expandable storage.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Microsoft",
                "price" => 60000,
                "screen_size" => 12.3,
                "processor" => "Intel Core i5",
                "storage" => "256GB SSD",
                "ram" => "766 grams",
                "description" => "Microsoft's Surface Pro tablet with an Intel Core i5 processor and fast SSD storage for productivity.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Amazon",
                "price" => 25000,
                "screen_size" => 8.0,
                "processor" => "Quad-Core",
                "storage" => "32GB",
                "ram" => "363 grams",
                "description" => "Amazon's budget-friendly Fire tablet with a quad-core processor and access to a wide range of apps and content.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Huawei",
                "price" => 30000,
                "screen_size" => 10.1,
                "processor" => "Kirin 710",
                "storage" => "64GB",
                "ram" => "450 grams",
                "description" => "Huawei's versatile tablet with a Kirin 710 processor and expandable storage for your multimedia needs.",
            ]
        ];

        $filteredProducts = array_filter($products, function ($product) use ($name, $brand) {
            $nameMatches = (strtolower($product['name']) === strtolower($name));
            $brandMatches = (strtolower($product['brand']) === strtolower($brand));
            return $nameMatches && $brandMatches;
        });

        return view('products', [
            'products' => $filteredProducts
        ]);
    }
    public function showProducts()
    {
        $products = [
            [
                "name" => "Laptop",
                "brand" => "Asus",
                "price" => 50000,
                "screen_size" => 15.6,
                "processor" => "Intel Core i7",
                "ram" => "16GB",
                "storage" => "512GB SSD",
                "description" => "A high-performance laptop from Asus with a powerful Intel Core i7 processor and ample RAM for multitasking.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Lenovo",
                "price" => 150000,
                "screen_size" => 14,
                "processor" => "Intel Core i9",
                "ram" => "32GB",
                "storage" => "1TB NVMe SSD",
                "description" => "Lenovo's flagship laptop featuring an Intel Core i9 processor and a spacious 1TB NVMe SSD for storage.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Dell",
                "price" => 75000,
                "screen_size" => 13.3,
                "processor" => "AMD Ryzen 9",
                "ram" => "16GB",
                "storage" => "512GB NVMe SSD",
                "description" => "A sleek and powerful Dell laptop with an AMD Ryzen 9 processor and fast NVMe SSD storage.",
            ],
            [
                "name" => "Laptop",
                "brand" => "HP",
                "price" => 60000,
                "screen_size" => 15.6,
                "processor" => "Intel Core i5",
                "ram" => "8GB",
                "storage" => "256GB SSD",
                "description" => "An affordable HP laptop with an Intel Core i5 processor and a speedy SSD for quick boot times.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Acer",
                "price" => 45000,
                "screen_size" => 14,
                "processor" => "AMD Ryzen 5",
                "ram" => "12GB",
                "storage" => "256GB SSD",
                "description" => "A budget-friendly Acer laptop powered by an AMD Ryzen 5 processor and ample RAM for smooth performance.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Mi",
                "price" => 20000,
                "screen_size" => 6.5,
                "processor" => "SD 780",
                "ram" => "8gb",
                "storage" => "128GB",
                "description" => "A budget-friendly Mi smartphone with a 48MP dual-camera setup and ample storage capacity.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Samsung",
                "price" => 25000,
                "screen_size" => 6.2,
                "processor" => "64MP Triple Camera",
                "storage" => "256GB",
                "ram" => "4500mAh",
                "description" => "Samsung's latest smartphone featuring a 64MP triple-camera system and a large battery for extended usage.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Apple",
                "price" => 80000,
                "screen_size" => 6.1,
                "processor" => "12MP Dual Camera",
                "storage" => "128GB",
                "ram" => "3800mAh",
                "description" => "The iconic iPhone from Apple with a powerful dual-camera system and ample storage for your apps and media.",
            ],
            [
                "name" => "Mobile",
                "brand" => "OnePlus",
                "price" => 35000,
                "screen_size" => 6.4,
                "processor" => "48MP Quad Camera",
                "storage" => "256GB",
                "ram" => "4200mAh",
                "description" => "OnePlus's flagship smartphone with a versatile quad-camera setup and generous storage capacity.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Google",
                "price" => 60000,
                "screen_size" => 5.8,
                "processor" => "12.2MP Rear Camera",
                "storage" => "128GB",
                "ram" => "3140mAh",
                "description" => "Google's Pixel phone known for its exceptional camera quality and clean Android experience.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Apple",
                "price" => 40000,
                "screen_size" => 10.2,
                "processor" => "Apple A13 Bionic",
                "storage" => "256GB",
                "ram" => "483 grams",
                "description" => "Apple's latest tablet with a powerful A13 Bionic chip and ample storage for all your needs.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Samsung",
                "price" => 35000,
                "screen_size" => 9.7,
                "processor" => "Samsung Exynos",
                "storage" => "128GB",
                "ram" => "420 grams",
                "description" => "Samsung's compact and lightweight tablet with a capable Exynos processor and expandable storage.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Microsoft",
                "price" => 60000,
                "screen_size" => 12.3,
                "processor" => "Intel Core i5",
                "storage" => "256GB SSD",
                "ram" => "766 grams",
                "description" => "Microsoft's Surface Pro tablet with an Intel Core i5 processor and fast SSD storage for productivity.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Amazon",
                "price" => 25000,
                "screen_size" => 8.0,
                "processor" => "Quad-Core",
                "storage" => "32GB",
                "ram" => "363 grams",
                "description" => "Amazon's budget-friendly Fire tablet with a quad-core processor and access to a wide range of apps and content.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Huawei",
                "price" => 30000,
                "screen_size" => 10.1,
                "processor" => "Kirin 710",
                "storage" => "64GB",
                "ram" => "450 grams",
                "description" => "Huawei's versatile tablet with a Kirin 710 processor and expandable storage for your multimedia needs.",
            ]
        ];


        return view('products', [
            'products' => $products,
        ]);
    }

    public function showByName($name)
    {
        $products = [
            [
                "name" => "Laptop",
                "brand" => "Asus",
                "price" => 50000,
                "screen_size" => 15.6,
                "processor" => "Intel Core i7",
                "ram" => "16GB",
                "storage" => "512GB SSD",
                "description" => "A high-performance laptop from Asus with a powerful Intel Core i7 processor and ample RAM for multitasking.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Lenovo",
                "price" => 150000,
                "screen_size" => 14,
                "processor" => "Intel Core i9",
                "ram" => "32GB",
                "storage" => "1TB NVMe SSD",
                "description" => "Lenovo's flagship laptop featuring an Intel Core i9 processor and a spacious 1TB NVMe SSD for storage.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Dell",
                "price" => 75000,
                "screen_size" => 13.3,
                "processor" => "AMD Ryzen 9",
                "ram" => "16GB",
                "storage" => "512GB NVMe SSD",
                "description" => "A sleek and powerful Dell laptop with an AMD Ryzen 9 processor and fast NVMe SSD storage.",
            ],
            [
                "name" => "Laptop",
                "brand" => "HP",
                "price" => 60000,
                "screen_size" => 15.6,
                "processor" => "Intel Core i5",
                "ram" => "8GB",
                "storage" => "256GB SSD",
                "description" => "An affordable HP laptop with an Intel Core i5 processor and a speedy SSD for quick boot times.",
            ],
            [
                "name" => "Laptop",
                "brand" => "Acer",
                "price" => 45000,
                "screen_size" => 14,
                "processor" => "AMD Ryzen 5",
                "ram" => "12GB",
                "storage" => "256GB SSD",
                "description" => "A budget-friendly Acer laptop powered by an AMD Ryzen 5 processor and ample RAM for smooth performance.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Mi",
                "price" => 20000,
                "screen_size" => 6.5,
                "processor" => "SD 780",
                "ram" => "8gb",
                "storage" => "128GB",
                "description" => "A budget-friendly Mi smartphone with a 48MP dual-camera setup and ample storage capacity.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Samsung",
                "price" => 25000,
                "screen_size" => 6.2,
                "processor" => "64MP Triple Camera",
                "storage" => "256GB",
                "ram" => "4500mAh",
                "description" => "Samsung's latest smartphone featuring a 64MP triple-camera system and a large battery for extended usage.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Apple",
                "price" => 80000,
                "screen_size" => 6.1,
                "processor" => "12MP Dual Camera",
                "storage" => "128GB",
                "ram" => "3800mAh",
                "description" => "The iconic iPhone from Apple with a powerful dual-camera system and ample storage for your apps and media.",
            ],
            [
                "name" => "Mobile",
                "brand" => "OnePlus",
                "price" => 35000,
                "screen_size" => 6.4,
                "processor" => "48MP Quad Camera",
                "storage" => "256GB",
                "ram" => "4200mAh",
                "description" => "OnePlus's flagship smartphone with a versatile quad-camera setup and generous storage capacity.",
            ],
            [
                "name" => "Mobile",
                "brand" => "Google",
                "price" => 60000,
                "screen_size" => 5.8,
                "processor" => "12.2MP Rear Camera",
                "storage" => "128GB",
                "ram" => "3140mAh",
                "description" => "Google's Pixel phone known for its exceptional camera quality and clean Android experience.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Apple",
                "price" => 40000,
                "screen_size" => 10.2,
                "processor" => "Apple A13 Bionic",
                "storage" => "256GB",
                "ram" => "483 grams",
                "description" => "Apple's latest tablet with a powerful A13 Bionic chip and ample storage for all your needs.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Samsung",
                "price" => 35000,
                "screen_size" => 9.7,
                "processor" => "Samsung Exynos",
                "storage" => "128GB",
                "ram" => "420 grams",
                "description" => "Samsung's compact and lightweight tablet with a capable Exynos processor and expandable storage.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Microsoft",
                "price" => 60000,
                "screen_size" => 12.3,
                "processor" => "Intel Core i5",
                "storage" => "256GB SSD",
                "ram" => "766 grams",
                "description" => "Microsoft's Surface Pro tablet with an Intel Core i5 processor and fast SSD storage for productivity.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Amazon",
                "price" => 25000,
                "screen_size" => 8.0,
                "processor" => "Quad-Core",
                "storage" => "32GB",
                "ram" => "363 grams",
                "description" => "Amazon's budget-friendly Fire tablet with a quad-core processor and access to a wide range of apps and content.",
            ],
            [
                "name" => "Tablet",
                "brand" => "Huawei",
                "price" => 30000,
                "screen_size" => 10.1,
                "processor" => "Kirin 710",
                "storage" => "64GB",
                "ram" => "450 grams",
                "description" => "Huawei's versatile tablet with a Kirin 710 processor and expandable storage for your multimedia needs.",
            ]
        ];

        $filteredProducts = array_filter($products, function ($product) use ($name) {
            return strtolower($product['name']) === strtolower($name);
        });

        return view('products', [
            'products' => $filteredProducts // Default brand if not provided
        ]);
    }
}
